name: Artifacts

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install gcc-arm-linux-gnueabihf
          rustup target add armv7-unknown-linux-gnueabihf

      - name: Build Artifact for amd64
        run: |
          cargo build --release

      - name: Build Artifact for raspberry pi
        run: |
          cargo build --target armv7-unknown-linux-gnueabihf --release

      - name: Upload Artifact for amd64
        uses: actions/upload-artifact@v2
        with:
          name: amd64 artifact
          path: target/release/jdav_server

      - name: Upload Artifact for amd64
        uses: actions/upload-artifact@v2
        with:
          name: armv7 artifact
          path: target/release/jdav_server
